### ISSUE TITLE
Enable deprecation of missing uploaded keys

### ISSUE THREAD

**Issue by dbenninger** [dwissk/oneskyapp-maven-plugin#2]
There is a flag "is_keeping_all_strings" in the API (see: https://github.com/onesky/api-documentation-platform/blob/master/resources/file.md#upload---upload-a-file). Setting this flag to false will deprecate (remove) the phrases in onesky that are missing/removed in the uploaded file. We use this quite often, because we constantly change our software, and add and remove translations from our files.

As far as I know, the plugin currently doesn't support this flag. It would be nice if it did.

**Comment by debueb** [comment]
I'm sorry, I don't understand the issue. @dbenninger could you please rephrase?

**Comment by dbenninger** [comment]
@debueb sorry about that. It was late evening. I hope it makes sense now..

**Comment by dwissk** [comment]
added support for this in 1.0.4

set `<isKeepingAllStrings>false</isKeepingAllStrings>` in upload `<configuration>` in order to remove obsolete strings from OneSkyApp

**Comment by debueb** [comment]
added support for this in 1.0.4, which will be available on maven central in a couple of minutes

set `<isKeepingAllStrings>false</isKeepingAllStrings>` in upload `<configuration>` in order to remove obsolete strings from OneSkyApp

**Comment by dbenninger** [comment]
Great, thank you!
